base_dir = "H:/silist/anime/illustration/pixiv_archived"
# base_dir = "E:/"
# base_dir = "/Users/feegao/Pictures/wallpaper"
# download_dir = "./wallpaper-recent"
download_dir = "G:/wallpaper/await"
addr = "192.168.0.176:3434"